/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SearchRouteImport } from './routes/search'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as MapRouteImport } from './routes/map'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminDemoRouteImport } from './routes/admin-demo'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketTicketIdRouteImport } from './routes/ticket.$ticketId'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDemoRoute = AdminDemoRouteImport.update({
  id: '/admin-demo',
  path: '/admin-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketTicketIdRoute = TicketTicketIdRouteImport.update({
  id: '/ticket/$ticketId',
  path: '/ticket/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin-demo': typeof AdminDemoRoute
  '/checkout': typeof CheckoutRoute
  '/data-sources': typeof DataSourcesRoute
  '/family': typeof FamilyRoute
  '/help': typeof HelpRoute
  '/map': typeof MapRoute
  '/plan': typeof PlanRoute
  '/queue': typeof QueueRoute
  '/search': typeof SearchRoute
  '/tickets': typeof TicketsRoute
  '/trips': typeof TripsRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin-demo': typeof AdminDemoRoute
  '/checkout': typeof CheckoutRoute
  '/data-sources': typeof DataSourcesRoute
  '/family': typeof FamilyRoute
  '/help': typeof HelpRoute
  '/map': typeof MapRoute
  '/plan': typeof PlanRoute
  '/queue': typeof QueueRoute
  '/search': typeof SearchRoute
  '/tickets': typeof TicketsRoute
  '/trips': typeof TripsRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin-demo': typeof AdminDemoRoute
  '/checkout': typeof CheckoutRoute
  '/data-sources': typeof DataSourcesRoute
  '/family': typeof FamilyRoute
  '/help': typeof HelpRoute
  '/map': typeof MapRoute
  '/plan': typeof PlanRoute
  '/queue': typeof QueueRoute
  '/search': typeof SearchRoute
  '/tickets': typeof TicketsRoute
  '/trips': typeof TripsRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/admin-demo'
    | '/checkout'
    | '/data-sources'
    | '/family'
    | '/help'
    | '/map'
    | '/plan'
    | '/queue'
    | '/search'
    | '/tickets'
    | '/trips'
    | '/ticket/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/admin-demo'
    | '/checkout'
    | '/data-sources'
    | '/family'
    | '/help'
    | '/map'
    | '/plan'
    | '/queue'
    | '/search'
    | '/tickets'
    | '/trips'
    | '/ticket/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/admin-demo'
    | '/checkout'
    | '/data-sources'
    | '/family'
    | '/help'
    | '/map'
    | '/plan'
    | '/queue'
    | '/search'
    | '/tickets'
    | '/trips'
    | '/ticket/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AdminDemoRoute: typeof AdminDemoRoute
  CheckoutRoute: typeof CheckoutRoute
  DataSourcesRoute: typeof DataSourcesRoute
  FamilyRoute: typeof FamilyRoute
  HelpRoute: typeof HelpRoute
  MapRoute: typeof MapRoute
  PlanRoute: typeof PlanRoute
  QueueRoute: typeof QueueRoute
  SearchRoute: typeof SearchRoute
  TicketsRoute: typeof TicketsRoute
  TripsRoute: typeof TripsRoute
  TicketTicketIdRoute: typeof TicketTicketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-demo': {
      id: '/admin-demo'
      path: '/admin-demo'
      fullPath: '/admin-demo'
      preLoaderRoute: typeof AdminDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$ticketId': {
      id: '/ticket/$ticketId'
      path: '/ticket/$ticketId'
      fullPath: '/ticket/$ticketId'
      preLoaderRoute: typeof TicketTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  AdminDemoRoute: AdminDemoRoute,
  CheckoutRoute: CheckoutRoute,
  DataSourcesRoute: DataSourcesRoute,
  FamilyRoute: FamilyRoute,
  HelpRoute: HelpRoute,
  MapRoute: MapRoute,
  PlanRoute: PlanRoute,
  QueueRoute: QueueRoute,
  SearchRoute: SearchRoute,
  TicketsRoute: TicketsRoute,
  TripsRoute: TripsRoute,
  TicketTicketIdRoute: TicketTicketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
